# Which will run 2 containers flask and mysql
# Create a network

version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: studentDB
    ports:
      - "3307:3306"
    networks:
      - docker-compose-flask-mysql-network
    volumes:
      - mysql-data:/var/lib/mysql

  flask:
    build:
      context: . 
    container_name: myflask-container
    ports:
      - "5001:5000"
    depends_on:
      - mysql
    networks:
      - docker-compose-flask-mysql-network

volumes:
  mysql-data:
  
networks:
  docker-compose-flask-mysql-network:
    driver: bridge
